# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='tracker.proto',
  package='tracker',
  serialized_pb='\n\rtracker.proto\x12\x07tracker\"k\n\x0eHelloToTracker\x12\x12\n\nsession_id\x18\x01 \x02(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\t\x12\x0c\n\x04port\x18\x03 \x02(\x05\x12\x13\n\x0b\x63lient_port\x18\x04 \x02(\x05\x12\x11\n\tavailable\x18\x05 \x02(\x05\"#\n\rHelloToClient\x12\x12\n\nsession_id\x18\x01 \x02(\x05\"\x9e\x01\n\x08NewBatch\x12\x12\n\nsession_id\x18\x01 \x02(\x05\x12\x12\n\nbatch_hash\x18\x02 \x02(\t\x12\r\n\x05tasks\x18\x03 \x02(\x05\x12/\n\nbatch_type\x18\x04 \x02(\x0e\x32\x1b.tracker.NewBatch.BatchType\"*\n\tBatchType\x12\x0c\n\x08RAYTRACE\x10\x00\x12\x0f\n\x0bPHOTSHOOTAH\x10\x01\"1\n\x0cNodesRequest\x12\x12\n\nsession_id\x18\x01 \x02(\x05\x12\r\n\x05nodes\x18\x02 \x02(\x05\"v\n\rNodesResponse\x12*\n\x05nodes\x18\x01 \x03(\x0b\x32\x1b.tracker.NodesResponse.Node\x1a\x39\n\x04Node\x12\x12\n\nsession_id\x18\x01 \x02(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\t\x12\x0c\n\x04port\x18\x03 \x02(\x05')



_NEWBATCH_BATCHTYPE = descriptor.EnumDescriptor(
  name='BatchType',
  full_name='tracker.NewBatch.BatchType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='RAYTRACE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PHOTSHOOTAH', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=289,
  serialized_end=331,
)


_HELLOTOTRACKER = descriptor.Descriptor(
  name='HelloToTracker',
  full_name='tracker.HelloToTracker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session_id', full_name='tracker.HelloToTracker.session_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='tracker.HelloToTracker.address', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='port', full_name='tracker.HelloToTracker.port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_port', full_name='tracker.HelloToTracker.client_port', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='available', full_name='tracker.HelloToTracker.available', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=133,
)


_HELLOTOCLIENT = descriptor.Descriptor(
  name='HelloToClient',
  full_name='tracker.HelloToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session_id', full_name='tracker.HelloToClient.session_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=135,
  serialized_end=170,
)


_NEWBATCH = descriptor.Descriptor(
  name='NewBatch',
  full_name='tracker.NewBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session_id', full_name='tracker.NewBatch.session_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='batch_hash', full_name='tracker.NewBatch.batch_hash', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tasks', full_name='tracker.NewBatch.tasks', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='batch_type', full_name='tracker.NewBatch.batch_type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NEWBATCH_BATCHTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=173,
  serialized_end=331,
)


_NODESREQUEST = descriptor.Descriptor(
  name='NodesRequest',
  full_name='tracker.NodesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session_id', full_name='tracker.NodesRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nodes', full_name='tracker.NodesRequest.nodes', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=333,
  serialized_end=382,
)


_NODESRESPONSE_NODE = descriptor.Descriptor(
  name='Node',
  full_name='tracker.NodesResponse.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session_id', full_name='tracker.NodesResponse.Node.session_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='tracker.NodesResponse.Node.address', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='port', full_name='tracker.NodesResponse.Node.port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=445,
  serialized_end=502,
)

_NODESRESPONSE = descriptor.Descriptor(
  name='NodesResponse',
  full_name='tracker.NodesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='nodes', full_name='tracker.NodesResponse.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NODESRESPONSE_NODE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=384,
  serialized_end=502,
)


_NEWBATCH.fields_by_name['batch_type'].enum_type = _NEWBATCH_BATCHTYPE
_NEWBATCH_BATCHTYPE.containing_type = _NEWBATCH;
_NODESRESPONSE_NODE.containing_type = _NODESRESPONSE;
_NODESRESPONSE.fields_by_name['nodes'].message_type = _NODESRESPONSE_NODE

class HelloToTracker(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLOTOTRACKER
  
  # @@protoc_insertion_point(class_scope:tracker.HelloToTracker)

class HelloToClient(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLOTOCLIENT
  
  # @@protoc_insertion_point(class_scope:tracker.HelloToClient)

class NewBatch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEWBATCH
  
  # @@protoc_insertion_point(class_scope:tracker.NewBatch)

class NodesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODESREQUEST
  
  # @@protoc_insertion_point(class_scope:tracker.NodesRequest)

class NodesResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Node(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _NODESRESPONSE_NODE
    
    # @@protoc_insertion_point(class_scope:tracker.NodesResponse.Node)
  DESCRIPTOR = _NODESRESPONSE
  
  # @@protoc_insertion_point(class_scope:tracker.NodesResponse)

# @@protoc_insertion_point(module_scope)
