# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='clientclient.proto',
  package='lightningclient',
  serialized_pb='\n\x12\x63lientclient.proto\x12\x0flightningclient\x1a\x0flightning.proto\"\x18\n\x05Hello\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\t\"\x18\n\x04Ping\x12\x10\n\x08pingdata\x18\x01 \x02(\x05\"\x18\n\x04Pong\x12\x10\n\x08pingdata\x18\x01 \x02(\x05\"3\n\x0e\x41llocateClient\x12\x0e\n\x06\x61mount\x18\x01 \x02(\x05\x12\x11\n\tbatchhash\x18\x02 \x02(\t\"8\n\x10\x41llocateResponse\x12\x0f\n\x07hasdata\x18\x01 \x02(\x08\x12\x13\n\x0bisavailable\x18\x02 \x02(\x08\"b\n\x04\x44\x61ta\x12\x11\n\tbatchhash\x18\x01 \x02(\t\x12\x10\n\x08\x64\x61tasize\x18\x02 \x02(\x05\x12\x10\n\x08\x64\x61tatype\x18\x03 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\t\x12\x15\n\rreturnaddress\x18\x05 \x02(\t\"m\n\x05Tasks\x12\x11\n\tbatchhash\x18\x01 \x02(\t\x12)\n\x04task\x18\x02 \x03(\x0b\x32\x1b.lightningclient.Tasks.Task\x1a&\n\x04Task\x12\x10\n\x08tasksize\x18\x01 \x02(\x05\x12\x0c\n\x04task\x18\x02 \x02(\t')




_HELLO = descriptor.Descriptor(
  name='Hello',
  full_name='lightningclient.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='address', full_name='lightningclient.Hello.address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=56,
  serialized_end=80,
)


_PING = descriptor.Descriptor(
  name='Ping',
  full_name='lightningclient.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pingdata', full_name='lightningclient.Ping.pingdata', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=106,
)


_PONG = descriptor.Descriptor(
  name='Pong',
  full_name='lightningclient.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pingdata', full_name='lightningclient.Pong.pingdata', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=108,
  serialized_end=132,
)


_ALLOCATECLIENT = descriptor.Descriptor(
  name='AllocateClient',
  full_name='lightningclient.AllocateClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='amount', full_name='lightningclient.AllocateClient.amount', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='batchhash', full_name='lightningclient.AllocateClient.batchhash', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=185,
)


_ALLOCATERESPONSE = descriptor.Descriptor(
  name='AllocateResponse',
  full_name='lightningclient.AllocateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hasdata', full_name='lightningclient.AllocateResponse.hasdata', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isavailable', full_name='lightningclient.AllocateResponse.isavailable', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=187,
  serialized_end=243,
)


_DATA = descriptor.Descriptor(
  name='Data',
  full_name='lightningclient.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='batchhash', full_name='lightningclient.Data.batchhash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datasize', full_name='lightningclient.Data.datasize', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datatype', full_name='lightningclient.Data.datatype', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='lightningclient.Data.data', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='returnaddress', full_name='lightningclient.Data.returnaddress', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=245,
  serialized_end=343,
)


_TASKS_TASK = descriptor.Descriptor(
  name='Task',
  full_name='lightningclient.Tasks.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tasksize', full_name='lightningclient.Tasks.Task.tasksize', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task', full_name='lightningclient.Tasks.Task.task', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=416,
  serialized_end=454,
)

_TASKS = descriptor.Descriptor(
  name='Tasks',
  full_name='lightningclient.Tasks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='batchhash', full_name='lightningclient.Tasks.batchhash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task', full_name='lightningclient.Tasks.task', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TASKS_TASK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=345,
  serialized_end=454,
)

import lightning_pb2

_TASKS_TASK.containing_type = _TASKS;
_TASKS.fields_by_name['task'].message_type = _TASKS_TASK

class Hello(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLO
  
  # @@protoc_insertion_point(class_scope:lightningclient.Hello)

class Ping(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PING
  
  # @@protoc_insertion_point(class_scope:lightningclient.Ping)

class Pong(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PONG
  
  # @@protoc_insertion_point(class_scope:lightningclient.Pong)

class AllocateClient(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALLOCATECLIENT
  
  # @@protoc_insertion_point(class_scope:lightningclient.AllocateClient)

class AllocateResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALLOCATERESPONSE
  
  # @@protoc_insertion_point(class_scope:lightningclient.AllocateResponse)

class Data(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATA
  
  # @@protoc_insertion_point(class_scope:lightningclient.Data)

class Tasks(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Task(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TASKS_TASK
    
    # @@protoc_insertion_point(class_scope:lightningclient.Tasks.Task)
  DESCRIPTOR = _TASKS
  
  # @@protoc_insertion_point(class_scope:lightningclient.Tasks)

# @@protoc_insertion_point(module_scope)
